import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Something Amazing...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href='../../styles/output.css>'></link> */}
      </Head>
      
      <main >
        <h2 className={"text-green-700"}> Please let there be something new? 2</h2>
      </main>
    </div>
  )
}
