import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Something Amazing...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href='../../styles/output.css>'></link> */}
      </Head>
      
      <main className='h-screen bg-gradient-to-b from-slate-900 to-slate-800'>
        {/* Headline Intorduction */}
        <h1 className="flex items-center place-content-center pt-12 text-white text-6xl font-bold"> 
          Something <a className='ml-4 underline text-blue-600 hover:text-blue-500' href=''>Amazing!</a>
        </h1>

        

      </main>
    </div>
  )
}
